version: '3.9'

services:
  marketplace-backend:
    build:
      dockerfile: ops/Dockerfile
    command: ./main
    ports:
      - 80:80
    depends_on:
      - postgresmp
    env_file:
      - ops/environment


  postgresmp:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5431:5432